name: FPGA core tests on NUC

on:
  push:
    branches:
      - main   # ajuste se quiser
  pull_request:
    branches:
      - main

jobs:
  fpga-core-test:
    runs-on: self-hosted
    # se você deu um label tipo NUC-FPGA lá no config.sh, pode usar:
    # runs-on: [self-hosted, NUC-FPGA]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull infra image
        run: |
          docker pull ghcr.io/pedropcventura/riscv-dev_tools:dev-amd64-final

      - name: Reset JTAG and run FPGA core tests
        run: |
          docker run --rm \
            --privileged \
            --device=/dev/bus/usb:/dev/bus/usb \
            -v "$PWD":/workspace \
            -w /workspace/tests/FPGA/core \
            ghcr.io/pedropcventura/riscv-dev_tools:dev-amd64-final \
            bash -lc "killall jtagd || true; jtagconfig; make"
